# Generated by Django 2.0.1 on 2018-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ResearchRequest',
        ),
    ]
